# Generated by Django 3.1 on 2020-08-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_log',
            name='change_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
