# Generated by Django 3.1 on 2020-08-11 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_relation',
            name='change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team_relation',
            name='check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team_relation',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='file_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user')),
            ],
            options={
                'db_table': 'file_log',
            },
        ),
    ]
