# Generated by Django 3.1 on 2020-08-12 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20200811_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team_relation',
            old_name='check',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='team_relation',
            name='delete',
        ),
        migrations.CreateModel(
            name='delete_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user')),
            ],
            options={
                'db_table': 'delete_date',
            },
        ),
    ]
