# Generated by Django 3.1 on 2020-08-12 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20200812_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(default='我想加入你们团队')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user')),
            ],
            options={
                'db_table': 'team_application',
            },
        ),
    ]
