# Generated by Django 3.1 on 2020-08-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_team_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_record',
            name='is_share',
            field=models.BooleanField(default=True),
        ),
    ]
