# Generated by Django 3.1 on 2020-08-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_team_record_is_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_record',
            name='is_share',
        ),
        migrations.AddField(
            model_name='file',
            name='is_share',
            field=models.BooleanField(default=True),
        ),
    ]
