# Generated by Django 3.1 on 2020-08-13 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20200813_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(default='我想邀请你加入我们团队')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user')),
            ],
            options={
                'db_table': 'team_invitation',
            },
        ),
    ]
