# Generated by Django 3.1 on 2020-08-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_team_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_record',
            name='is_creator',
            field=models.BooleanField(default=True),
        ),
    ]
