# Generated by Django 3.1 on 2020-08-16 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_cooperate_invitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_collection',
            old_name='file',
            new_name='files',
        ),
    ]
