# Generated by Django 3.1 on 2020-08-16 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20200816_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='消息标题', max_length=128)),
                ('content', models.TextField(default='消息内容')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Templete_grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('templete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user')),
            ],
            options={
                'db_table': 'templete_grade',
            },
        ),
        migrations.CreateModel(
            name='Message_to_invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.message')),
                ('team_invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.team_invitation')),
            ],
            options={
                'db_table': 'message_to_invitation',
            },
        ),
    ]
